apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 1
    defaultRequest:
      memory: 100Mi
      cpu: 500m
    type: Container
