apiVersion: v1
kind: Pod
metadata:
  name: busybox 
  namespace: default
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /mysqlpassword
      name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql
            key: password
  volumes:
  - name: mysql
    secret:
      secretName: mysql